### ISSUE TITLE
Close to tray feature request

### ISSUE THREAD

**Issue by PS-Professional** [Windscribe/Desktop-App#18] opened 2022-01-31 19:57 UTC
Hi there.

The Windscribe app on Ubuntu doesn't have a "Close to tray" feature, so you have to keep the window opened and if you try to close it, the process will end and it won't continue in the background. Can you add it to the program?

Thank you for developing this app.

**Comment by yegors** [comment] 2022-01-31 20:34
But, can't you just minimize the app to tray? That would accomplish the exact same thing as "close to tray" option.

**Comment by PS-Professional** [comment] 2022-01-31 20:39
> But, can't you just minimize the app to tray? That would accomplish the exact same thing as "close to tray" option.

Minimizing is possible but it make it messy in app section

**Comment by yegors** [comment] 2022-01-31 20:46
Do you have an example of an app that implements the desired behavior? We're not sure if this is possible in some/all Linux GUI shells.

**Comment by PS-Professional** [comment] 2022-01-31 20:53
Outline Client works like that.
Although you can't change the behavior, by closing the open window, it just continues to work in the background.

**Comment by jaxu** [comment] 2022-04-29 17:56
@PS-Professional @par3ae

Folks, we have a preview build with the minimize & close to tray feature for Linux which I've attached to this comment.  We would really appreciate any feedback on whether the feature works as you expect it to

Thanks!

[windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip](https://github.com/Windscribe/Desktop-App/files/8592751/windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip)

**Comment by par3ae** [comment] 2022-04-30 06:38
> @PS-Professional @par3ae
> 
> Folks, we have a preview build with the minimize & close to tray feature for Linux which I've attached to this comment. We would really appreciate any feedback on whether the feature works as you expect it to
> 
> Thanks!
> 
> [windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip](https://github.com/Windscribe/Desktop-App/files/8592751/windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip)

Hi dear jaxu
yeah that's great now and work properly
but just a simple thing:
when app closed to tray, left click on it take no action and if again we want the app to come up, we should right click on it and click "show".
It would be great if app come up by just left click on it in tray.

Thanks a lot

**Comment by PS-Professional** [comment] 2022-04-30 06:44
> > @PS-Professional @par3ae
> > Folks, we have a preview build with the minimize & close to tray feature for Linux which I've attached to this comment. We would really appreciate any feedback on whether the feature works as you expect it to
> > Thanks!
> > [windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip](https://github.com/Windscribe/Desktop-App/files/8592751/windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip)
> 
> Hi dear jaxu yeah! that's great now and works properly but just a simple thing: when Windscribe closed to tray, left click on it take no action and if again we want the app to come up, we should right click on it and click "show". It would be great if app come up by just left click on it in tray.
> 
> Thanks a lot

Yeah, I agree with that.

**Comment by jaxu** [comment] 2022-04-30 13:21
> > > @PS-Professional @par3ae
> > > Folks, we have a preview build with the minimize & close to tray feature for Linux which I've attached to this comment. We would really appreciate any feedback on whether the feature works as you expect it to
> > > Thanks!
> > > [windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip](https://github.com/Windscribe/Desktop-App/files/8592751/windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip)
> > 
> > 
> > Hi dear jaxu yeah! that's great now and works properly but just a simple thing: when Windscribe closed to tray, left click on it take no action and if again we want the app to come up, we should right click on it and click "show". It would be great if app come up by just left click on it in tray.
> > Thanks a lot
> 
> Yeah, I agree with that.

Thanks to both of you for your feedback!  I'll make that change before the release.

**Comment by par3ae** [comment] 2022-05-05 09:44
> > > > @PS-Professional @par3ae
> > > > Folks, we have a preview build with the minimize & close to tray feature for Linux which I've attached to this comment. We would really appreciate any feedback on whether the feature works as you expect it to
> > > > Thanks!
> > > > [windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip](https://github.com/Windscribe/Desktop-App/files/8592751/windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip)
> > > 
> > > 
> > > Hi dear jaxu yeah! that's great now and works properly but just a simple thing: when Windscribe closed to tray, left click on it take no action and if again we want the app to come up, we should right click on it and click "show". It would be great if app come up by just left click on it in tray.
> > > Thanks a lot
> > 
> > 
> > Yeah, I agree with that.
> 
> Thanks to both of you for your feedback! I'll make that change before the release.

Hi again dear jaxu
I saw another bug in this release:
When I enable "Launch on Startup" option, It starts successfully when linux starts but all my favorites locations cleaned and all news feeds marked as unread.
please fix it
thanks

**Comment by jaxu** [comment] 2022-05-05 13:02
> Hi again dear jaxu I saw another bug in this release: When I enable "Launch on Startup" option, Windscribe starts successfully when linux starts but all my favorites locations was cleaned and all news feeds marked as unread. please fix it thanks

Hi par3ae, can you tell me if this is related with the close-to-tray feature?  If not, can you please open a new issue for the problem you're seeing, and we will have someone look into it as soon as possible.  Please include as much information as you can.  Thank you.

**Comment by PS-Professional** [comment] 2022-05-05 13:39
> > Hi again dear jaxu I saw another bug in this release: When I enable "Launch on Startup" option, Windscribe starts successfully when linux starts but all my favorites locations was cleaned and all news feeds marked as unread. please fix it thanks
> 
> Hi par3ae, can you tell me if this is related with the close-to-tray feature? If not, can you please open a new issue for the problem you're seeing, and we will have someone look into it as soon as possible. Please include as much information as you can. Thank you.

Well, I didn't noticed it myself but it's probably a separate issue from the new feature.

**Comment by par3ae** [comment] 2022-05-05 15:28
> > Hi again dear jaxu I saw another bug in this release: When I enable "Launch on Startup" option, Windscribe starts successfully when linux starts but all my favorites locations was cleaned and all news feeds marked as unread. please fix it thanks
> 
> Hi par3ae, can you tell me if this is related with the close-to-tray feature? If not, can you please open a new issue for the problem you're seeing, and we will have someone look into it as soon as possible. Please include as much information as you can. Thank you.

No it's not related to close-to-tray feature.
My favorites locations cleaned after restart whether close-to-tray feature is active or not.
Should I open a new issue?

**Comment by jaxu** [comment] 2022-05-06 13:23
> > > Hi again dear jaxu I saw another bug in this release: When I enable "Launch on Startup" option, Windscribe starts successfully when linux starts but all my favorites locations was cleaned and all news feeds marked as unread. please fix it thanks
> > 
> > 
> > Hi par3ae, can you tell me if this is related with the close-to-tray feature? If not, can you please open a new issue for the problem you're seeing, and we will have someone look into it as soon as possible. Please include as much information as you can. Thank you.
> 
> No it's not related to close-to-tray feature. My favorites locations cleaned after restart whether close-to-tray feature is active or not. Should I open a new issue?

Yes, if you notice any oddities, especially regressions from past releases, please go ahead and open a new issue and we'll have someone look at it as soon as possible.  Thanks.

**Comment by par3ae** [comment] 2022-05-28 06:23
> > > > @PS-Professional @par3ae
> > > > Folks, we have a preview build with the minimize & close to tray feature for Linux which I've attached to this comment. We would really appreciate any feedback on whether the feature works as you expect it to
> > > > Thanks!
> > > > [windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip](https://github.com/Windscribe/Desktop-App/files/8592751/windscribe_2.4.5_beta_amd64_linux_tray_menu.deb.zip)
> > > 
> > > 
> > > Hi dear jaxu yeah! that's great now and works properly but just a simple thing: when Windscribe closed to tray, left click on it take no action and if again we want the app to come up, we should right click on it and click "show". It would be great if app come up by just left click on it in tray.
> > > Thanks a lot
> > 
> > 
> > Yeah, I agree with that.
> 
> Thanks to both of you for your feedback! I'll make that change before the release.

Hi again dear jaxu
excuse me, is there an estimate time to release stable version?
It crashed sometimes on my system

**Comment by jaxu** [comment] 2022-05-28 15:51
> Hi again dear jaxu excuse me, is there an estimate time to release stable version? It crashed sometimes on my system

Hi there!  We currently plan to release the feature in 2.5, but we don't have a time estimate yet.  If you are seeing any crashes in this build not related to the minimize to tray feature, PLEASE raise a new issue with more details since we'd love to address that as soon as possible.  Thanks!

**Comment by bernerdad** [comment] 2022-09-23 21:18
Hi.  v2.5.6 is available in our guinea pig channel, and it resolves this issue.  Cheers!

**Closed by bernerdad** 2022-09-23 21:18 UTC
