### ISSUE TITLE
Right click system tray not working randomly

### ISSUE THREAD

**Issue by sith-on-mars** [Windscribe/Desktop-App#84] opened 2023-03-17 04:55 UTC
OS: OpenSUSE MicroOS Gnome (an immutable OS, uses systemd)
App version: v2.6.12

<strike>Right clicking system tray doesn't do anything. It was working fine in v2.6.6.<strike>

The right-click works sometimes but randomly stops working.

**Comment by bernerdad** [comment] 2023-03-23 17:54
Hi.  We're unable to reproduce this behavior on our supported distros.  We've made a note to investigate it if we add this OS to said list.

**Comment by sith-on-mars** [comment] 2023-03-23 19:30
Thanks! Did you test it on Gnome? Not sure if it might be a Gnome specific issue.

**Comment by bernerdad** [comment] 2023-03-23 19:56
Yes.  Tested on Gnome 42.5 and the Wayland windowing system (Ubuntu 22.04).

**Comment by sith-on-mars** [comment] 2023-03-24 03:50
The right-click works sometimes but randomly stops working in my case.

**Comment by bernerdad** [comment] 2023-11-03 19:16
Hi.  Can you please let us know if this issue still occurs in our latest guinea pig build?  Thanks!
https://deploy.totallyacdn.com/desktop-apps/2.8.1/Windscribe_2.8.1_guinea_pig.exe

**Comment by bernerdad** [comment] 2023-11-25 20:28
Closing as not reproducible in supported builds.

**Closed by bernerdad** 2023-11-25 20:28 UTC
