### ISSUE TITLE
Build windscribe for arm64

### ISSUE THREAD

**Issue by leana8959** [Windscribe/Desktop-App#26] opened 2022-02-27 21:04 UTC
I want to install windscribe on ubuntu 20.04 arm64, I suppose the source code on this repository is only for amd64 as I can't seem to complete `./build_all`. The error looks like this:
```
INFO: Creating Debian package...
dpkg-deb: building package 'windscribe' in '/home/parallels/Desktop-App/temp/installer/InstallerFiles/../windscribe_2.4.1_amd64.deb'.
Traceback (most recent call last):
  File "./build_all.py", line 855, in <module>
    pre_checks_and_build_all()
  File "./build_all.py", line 811, in pre_checks_and_build_all
    build_all(win_cert_password)
  File "./build_all.py", line 718, in build_all
    build_installer_linux(configdata, qt_root)
  File "./build_all.py", line 654, in build_installer_linux
    dest_package_path + ".deb"])
  File "/home/parallels/Desktop-App/tools/deps/installutils.py", line 180, in RunCommand
    proc.ExecuteWithRealtimeOutput(command_and_args, env=env, shell=shell)
  File "/home/parallels/Desktop-App/tools/base/process.py", line 27, in ExecuteWithRealtimeOutput
    process_handle = subprocess.Popen(command_and_args, stdout=subprocess.PIPE, env=env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
It would be awesome to be able to install windscribe on arm64 linux platforms.

Thank you !

**Comment by alok-sin** [comment] 2022-03-06 02:16
This is duplicate of #9

**Comment by leana8959** [comment] 2023-01-26 18:00
> This is duplicate of #9 

Considering that Linux aarch64 and macOS aarch64 are quite different, is this still a duplicate of #9?

**Comment by bernerdad** [comment] 2023-01-26 18:49
Definitely not a duplicate of #9.  We've completed the port to Apple silicon, and the port to Windows-on-Arm will be next.  Are there any readily available commercial Linux-on-Arm laptops or desktops devices?

**Comment by leana8959** [comment] 2023-01-26 21:40
I'm not sure. What I wanted was to install Windscribe GUI on a Linux VM on my Apple Silicon Mac, or on a Raspberry Pi. Would it be complicated to achieve that?

**Comment by bernerdad** [comment] 2023-01-26 22:46
It would be somewhat complicated, which is why we've been postponing this port until the Linux distros we support (Ubuntu/Fedora) are available for arm64 and there are readily available laptops/desktops with arm64 CPUs.

**Comment by bernerdad** [comment] 2023-03-30 22:54
Support for Ubuntu arm64 is planned for the v2.7 release, which is underway now.

**Comment by moadle** [comment] 2023-08-24 05:57
> Here's our very first official guinea pig build for Ubuntu arm64: https://deploy.totallyacdn.com/desktop-apps/2.7.3/windscribe_2.7.3_guinea_pig_arm64.deb

Could you consider making it compatible for Raspberry Pi OS also, I tried the guinea_pig build, it works fine on Raspberry Pi with Ubuntu but wouldn't boot up on RPi OS.

**Comment by bernerdad** [comment] 2023-10-04 20:18
Closing this issue as the app now fully supports Ubuntu arm64.

**Closed by bernerdad** 2023-10-04 20:18 UTC
