### ISSUE TITLE
Windscribe helper initialize error. Please reinstall the application or contact support. - Fedora Kinoite (SilverBlue)

### ISSUE THREAD

**Issue by Linux-Is-Best** [Windscribe/Desktop-App#109] opened 2023-10-16 23:28 UTC
From the terminal

`
[{gmt_time}      0.018] [basic]  App start time: "Mon Oct 16 18:20:15 2023"
[{gmt_time}      0.018] [basic]  App version: "v2.6.14"
[{gmt_time}      0.018] [basic]  Platform: "wayland"
[{gmt_time}      0.018] [basic]  OS Version: "Linux #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:57:21 UTC 2023"
[{gmt_time}      0.018] [basic]  CPU architecture: "x86_64"
[{gmt_time}      0.023] [basic]  Detected OpenVPN versions: QList("2.5.4")
[{gmt_time}      0.023] [basic]  Selected OpenVPN version: "2.5.4"
[{gmt_time}      0.023] [basic]  DpiScaleManager::constructor -> DPI: 96 ; scale: 1 ; devicePixelRatio: 1
[{gmt_time}      0.028] [basic]  OS in dark mode:  true
[{gmt_time}      0.045] [basic]  GUI pid:  16088
[{gmt_time}      0.046] [basic]  Gui settings {isLaunchOnStartup:true; isAutoConnect:false; isHideFromDock:false; isShowNotifications:false; orderLocation:"Geography"; latencyDisplay:"Bars"; shareSecureHotspot:{isEnabled:false; ssid:empty; password:empty}; shareProxyGateway:{isEnabled:false; proxySharingMode:"HTTP"}; splitTunneling:{settings:{active:false; mode:"Exclude"}; apps:QList(); networkRoutes:QList()}; isDockedToTray:false; isMinimizeAndCloseToTray:false; backgroundSettings:{backgroundType:1; backgroundImageDisconnected:empty; backgroundImageConnected:empty}; isStartMinimized:false; isShowLocationHealth:false; isAutoSecureNetworks:true; appSkin:"Alpha"}
[{gmt_time}      0.047] [basic]  Engine settings {language:"en"; updateChannel:"Release"; isIgnoreSslErrors:false; isTerminateSockets:true; isAllowLanTraffic:false; firewallSettings: {mode:"Automatic"; when:"Before Connection"}; connectionSettings: {isAutomatic:true; protocol:"WireGuard"; port:443}; dnsResolutionSettings: {isAutomatic:true; manualAddress:""}; proxySettings: {option:"None"; address:""; port:0; username:empty; password:empty}; packetSize: {isAutomatic:true; mtu:-1}; macAddrSpoofing: {isEnabled:false; macAddress:""; selectedNetworkInterface:{friendlyName:""; networkOrSsid:""}; networkInterfaces:{}; dnsPolicy: "Cloudflare"; customOvpnConfigsPath: empty; isKeepAliveEnabled:false; connectedDnsInfo:{type:0}; dnsManager:"Automatic"; networkPreferredProtocols:QMap(); networkLastKnownGoodProtocols: {QMap(); }}
[{gmt_time}      0.227] [basic]  Backend::init()
[{gmt_time}      0.227] [basic]  Error while connecting to helper (first):  2
[{gmt_time}      0.236] [basic]  setWindowPosFromPersistent() - screen "HDMI-A-1" - geometry QRect(0,0 1920x1080) - virtualGeometry QRect(0,0 1920x1080) - logicalDotsPerInch 96 - devicePixelRatio 1
[{gmt_time}      0.237] [basic]  setWindowPosFromPersistent() - restored app geometry: QRect(764,352 392x376)
[{gmt_time}      0.237] [basic]  Tray Icon geometry: QRect(0,0 0x0)
[{gmt_time}      0.251] [basic]  DpiScaleManager::setMainWindow -> no DPI or pixel ratio changes
[{gmt_time}      0.311] [basic]  ImageResourcesSvg::run() - all SVGs loaded
[{gmt_time}      5.231] [basic]  Error while connecting to helper:  2
[{gmt_time}      5.238] [basic]  OpenVPN helper connect failed
[{gmt_time}      5.238] [basic]  Attempt to reinstall helper
[{gmt_time}      5.238] [basic]  Failed reinstall helper

`

**Comment by bernerdad** [comment] 2023-10-17 14:59
Duplicate of #88 and related to #82.  We do not currently support Fedora SilverBlue.  Sorry!

**Closed by bernerdad** 2023-10-17 14:59 UTC
