### ISSUE TITLE
Tray icon theme

### ISSUE THREAD

**Issue by anfokaboom** [Windscribe/Desktop-App#74] opened 2022-12-18 09:34 UTC
Hi
Using ZorinOS 16.2. Is there a colour other than white for the system tray icon? I've looked within preferences for a way to change to any other colour, but have been unsuccessful.

Hopefully I haven't been blind to an obvious setting.

**Comment by bernerdad** [comment] 2022-12-19 18:14
Hi.  There isn't a way to change the colour of the system tray icon.  It will be white for systems in dark mode, and black otherwise.

**Comment by anfokaboom** [comment] 2022-12-19 23:15
I wish that were the case. I guess I'm in dark mode because that is the only way I'll see the icon. Please consider icon colours.

**Comment by ksz16** [comment] 2023-06-09 06:44
Similar problem on Arch Linux with LXQt (1.3.0). Despite selecting a light theme, the tray icon is still white. I don't know if the problem is on the Windscribe side, or if it's more a problem with LXQt. But it would be nice if Windscribe offered automatic mode and in addition manually selectable light and dark modes (as far as I remember KeePassXC solves the problem this way).
Please, consider my request, because the light icon against the white bar makes it difficult for me to use the application.

**Comment by bernerdad** [comment] 2023-06-12 23:30
Apologies, as I was mistaken in my previous response.  The tray icon on Linux is currently set to always be white, regardless of OS theme.  We'll fix this oversight asap.

**Comment by ksz16** [comment] 2023-10-25 06:19
I installed version 2.7.14 today, and the problem with the color of the tray icon is still unsolved - the icon is white despite the light system theme (Arch Linux with LXQt 1.3.0)

**Comment by bernerdad** [comment] 2023-10-25 15:59
Hi.  One of our devs is working on this right now.  I'll post a link here when a guinea pig build is available containing this fix.

**Comment by ksz16** [comment] 2023-10-26 09:59
OK, so I am waiting for the link - I will test the app and let you know. Thanks.

**Comment by bernerdad** [comment] 2023-11-02 20:28
We have added a preference allowing you to select your tray icon color.  Please let us know if it works on your distro.
https://deploy.totallyacdn.com/desktop-apps/2.8.1/Windscribe_2.8.1_guinea_pig.exe

**Comment by ksz16** [comment] 2023-11-03 09:34
I ran a quick tests. Below are the results.

Debian 12 + MATE 1.26.0 and Lubuntu 23.10:
application installed correctly, but won't start.
To be honest, I didn't have time to dig deep into the topic, but I'm sending an error message (maybe it will be useful).

```
[{gmt_time}      0.001] [qt.qpa.plugin]	 Could not load the Qt platform plugin "xcb" in "" even though it was found.
[{gmt_time}      0.001] [default]	 This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: xcb, wayland, wayland-egl.
Aborted
```

Arch Linux + LXQt 1.3:
application installed correctly, starts without any problems. The ability to change the color of the icon in the tray works correctly.

**Comment by ksz16** [comment] 2023-11-03 09:46
I have one more question: I noticed that networkmanager and wpa_supplicant appeared as new dependencies during installation in Arch Linux. Is this necessary? I use connman instead of networkmanager. Besides, not all machines have wifi cards, so wpa_supplicant is not always needed. In earlier versions networkmanager was not a dependency and the application worked very well with connman.

**Comment by jaxu** [comment] 2023-11-03 14:59
> I ran a quick tests. Below are the results.
> 
> Debian 12 + MATE 1.26.0 and Lubuntu 23.10: application installed correctly, but won't start. To be honest, I didn't have time to dig deep into the topic, but I'm sending an error message (maybe it will be useful).
> 
> ```
> [{gmt_time}      0.001] [qt.qpa.plugin]	 Could not load the Qt platform plugin "xcb" in "" even though it was found.
> [{gmt_time}      0.001] [default]	 This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> Available platform plugins are: xcb, wayland, wayland-egl.
> Aborted
> ```
> 
> Arch Linux + LXQt 1.3: application installed correctly, starts without any problems. The ability to change the color of the icon in the tray works correctly.

Thanks for the report.  I'll look into this.

**Comment by jaxu** [comment] 2023-11-03 15:01
> I have one more question: I noticed that networkmanager and wpa_supplicant appeared as new dependencies during installation in Arch Linux. Is this necessary? I use connman instead of networkmanager. Besides, not all machines have wifi cards, so wpa_supplicant is not always needed. In earlier versions networkmanager was not a dependency and the application worked very well with connman.

Yes, we use nmcli in various places in the application to determine various network status.  It was a missing dependency in previous versions which caused some functionality to be broken when it wasn't installed.  wpa_supplicant is pulled in indirectly by networkmanager I believe.  Your feedback is noted and we'll try to streamline this further in future releases.

**Comment by ksz16** [comment] 2023-11-03 20:25
As for networkmanager: I understand - if this only makes the application more secure and stable, then I have no objections. 
You are right: in Arch wpa_supplicant is a dependency of networkmanager.
Thanks for the info.

I'm waiting for the next version - each next build makes the application more and more mature.
And thanks to the whole team for your work.

**Comment by bernerdad** [comment] 2023-11-18 22:54
We've fixed the problem of missing deps in this build.  Closing this issue as fixed.  Cheers!
https://deploy.totallyacdn.com/desktop-apps/2.8.2/windscribe_2.8.2_guinea_pig_amd64.deb

**Closed by bernerdad** 2023-11-18 22:54 UTC
